### ISSUE TITLE
rdp_accountant.py 　　Function understanding

### ISSUE THREAD

**Issue by PualTorresZhang** [tensorflow/privacy#13]
I'm new to DP, it's hard for me to understand some functions especially '_compute_rdp' , '_compute_log_a'
is there some papers i can reference? Thanks!:)

**Comment by npapernot** [comment]
You can learn more about the RDP accountant specifically in the following paper: https://arxiv.org/abs/1702.07476

If you'd like to understand the overall approach to SGD with differential privacy, the following paper will be a better start: https://arxiv.org/abs/1607.00133
