### ISSUE TITLE
How to compute the epsilon achieved if the noise_multiplier dynamically changes for each training step?

### ISSUE THREAD

**Issue by AshiakerWang** [tensorflow/privacy#132]
For current implementation of the function computing the epsilon achieved, the parameter **noise_multiplier** is fixed during the training process:
 https://github.com/tensorflow/privacy/blob/1981ebe2f2eecf5c7962c45ed95a4d5d3f2a82d5/tensorflow_privacy/privacy/analysis/rdp_accountant.py#L293

I wonder how to compute the epsilon achieved after training if the noise_multiplier **dynamically changes** for each training step?

**Comment by galenmandrew** [comment]
If you use the privacy ledger and compute_rdp_from_ledger, you can compute the epsilon for an arbitrary sequence of noise_stddev and l2_norm_bound.

**Comment by AshiakerWang** [comment]
> If you use the privacy ledger and compute_rdp_from_ledger, you can compute the epsilon for an arbitrary sequence of noise_stddev and l2_norm_bound.


I just found the following function:
https://github.com/tensorflow/privacy/blob/1981ebe2f2eecf5c7962c45ed95a4d5d3f2a82d5/tensorflow_privacy/privacy/analysis/rdp_accountant.py#L267-L268

Can this function do the same work as the method you offered?

**Comment by galenmandrew** [comment]
Yes I wasn't aware of that but it seems to do the same thing using python
lists instead of a ledger.

**Comment by AshiakerWang** [comment]
Thank you for the detailed responses and all the help
