### ISSUE TITLE
compute_rdp_from_ledger is slow and can be made faster by grouping

### ISSUE THREAD

**Issue by MatteoGiomi** [tensorflow/privacy#165]
Hi, 

The function `rdp_accountant.compute_rdp_from_ledger` can be pretty slow if the ledger contains many entries. The bottleneck are the calls to [`compute_rdp(..., step=1, ..)`](https://github.com/tensorflow/privacy/blob/master/tensorflow_privacy/privacy/analysis/rdp_accountant.py#L393) inside the loop.

This can be optimized by inspecting the ledger content using `collections.Counter` to group together all the steps that shares the same parameters. Instead of calling `compute_rdp` with 1 single step for each entry, you just call it for each group of steps with same noise multiplier and sampling probability. 

In the case in which there are many repeated entries in the ledger (I think it's pretty common), the benefit of this approach can be pretty substantial. If you think this can be useful I can prepare a PR. 

thanks a lot, 
Matteo

**Comment by galenmandrew** [comment]
Hi Matteo, thanks for the optimization idea! Normally we'd happily accept your PR, but we're actually in the process of a major overhaul to the way privacy logging and accounting is handled, so I'm afraid this optimization would only be useful for another month or two. We will however keep this type of bottleneck in mind while implementing the new accountant.

**Comment by MatteoGiomi** [comment]
Hi Andrew, 

thanks for the quick reply. I'm happy to hear that new stuff is coming up soon, I'm looking forward to it! Let me know if there is anything I can do to help. 

Have a good day, 
Matteo
