### ISSUE TITLE
Reproducing values from Learning differentially private recurrent language models (McMahan, H. B., et al 2017)

### ISSUE THREAD

**Issue by JoaquinDF** [tensorflow/privacy#174]
Dear TensorFlow Privacy Authors,
First of all Thank you for your work on this repo.

I do have a question about the reproducibility of the paper **Learning differentially private recurrent language models**

### Overview

I am trying to reproduce some of the values regarding the privacy guarantee.

### Procedure
 
To do so I followed this answer from @jkr26 on [stackoverflow](https://stackoverflow.com/questions/65943395/track-privacy-guarantees-in-a-federated-learning-process-with-dp-query)
Here is the code i used:
```
def compute_fl_privacy(num_rounds, noise_multiplier,delta, num_users, users_per_round):
  # This actually assumes Poisson subsampling, which may not be *quite*
  # right in your setting, but the approximation should be close either way.
    q = users_per_round / num_users  # q - the sampling ratio.

    # These orders are inlined from the body of compute_dp_sgd_privacy
    orders = [1 + x / 100. for x in range(1, 1000)] + list(range(12, 64))
    # Depending on whether your TFF code by default uses adaptive clipping or not,
    # you may need to rescale your noise_multiplier argument.

    return apply_dp_sgd_analysis(
    q, sigma=noise_multiplier, steps=num_rounds, orders=orders, delta=delta)
```
Reproducing it with:
- Noise std dev = 0.012
- L2 norm bound = 15
- Number of users = 763430
- Users per rounds = 1250
- Number of rounds = 3000
-  delta = 10e-9
 
I call:
```
compute_fl_privacy(3000,0.012,10e-09,763430,1250)

DP-SGD with sampling rate = 0.164% and noise_multiplier = 0.012 iterated over 3000 steps satisfies differential privacy with eps = 9.64e+06 and delta = 1e-08.
The optimal RDP order is 1.02.

```
The values that I am getting are way to different compared with the results of the paper. 
My privacy guarantee (9.64e06 -10e-9) 
 McMahan, H. B., et al 2017 privacy guarantee (1.97-10e-9) 

Do you have any idea why I am getting these results and how can I replicate the results of the paper?

Thank you!

**Comment by kairouzp** [comment]
One obvious error is that you should be using a `noise_multiplier = 1` because the `query_sensitivity = 15/1250 = 0.012` and you are adding a `noise_std_dev = 0.012` (`noise_multiplier = noise_std_dev/ query_sensitivity`). 

That said, do not expect to get the number you will get to match exactly the number shown in the paper. We have recently improved the DP accounting code, so you must get a better (i.e. smaller) epsilon. 

Please let me know if you still have any questions.

**Comment by hbmcmahan** [comment]
Thank you for the question, and the clear code to reproduce the issue. Sorry I had missed this earlier, pasting the reply I'd sent over email to Joaquín, which provides a bit more detail on the point kairouzp made.

> I assume you are taking the clipping norm S=1 in your calculation? The key is then in the calculation of the noise multiplier, which is the ratio of the stddev of the noise to the sensitivity of the query. In this case, the sensitivity is given by Lemma 1, and if we are doing sampling and uniformly weighting clients, then W = num_users, and qW ~= num_clients_per_round  (technically qW is the *expected* number of users per round), and so we have noise_multiplier = num_clients_per_round * 0.012.  In practice, we usually work the other way: once we identify a tolerable level of noise, we can solve for the num_clients_per_round necessary to achieve a small noise multiplier (or a particular epsilon using line search on the full privacy accounting). E.g., on page 7/8  "Continuing the above example, if instead we choose q so C˜ = 1250, set the L2 norm bound S = 15.0, then we have sensitivity 15/1250 = 0.012, and so we add noise σ = 0.012 and can apply the moments account with noise scale z = 1. The computation is now significantly more computationally expensive, but will give a guarantee of (1.97, 10−9 )-differential privacy after 3000 rounds of training."
