### ISSUE TITLE
Pip Install error

### ISSUE THREAD

**Issue by greninja** [tensorflow/privacy#2]
As far as I know, `pip` install requires a `setup.py` file. 
Running the command given in the "Installing TensorFlow Privacy" (`pip install -e ./privacy`)
throws the following error:

   `Directory './privacy' is not installable. File 'setup.py' not found.`

Am I missing something here?

**Comment by npapernot** [comment]
That's correct, we forgot to include a setup.py file. Thank you for letting us know.

**Comment by greninja** [comment]
Sure. Will close this once added.

**Comment by npapernot** [comment]
It was just added, feel free to reopen if this does not address your issue.

**Comment by greninja** [comment]
You have added it in the root folder. Changing `pip install -e ./privacy` to `pip install -e .` in the README
should do the job :)

**Comment by greninja** [comment]
I hope opening a PR is not required for this?

**Comment by knaggita** [comment]
> pip install -e .

Worked for me.

**Comment by npapernot** [comment]
No, thanks for catching that in the README. I will roll out an update to the README in the next revision.

**Comment by npapernot** [comment]
The README was just updated, thanks again for spotting this.
