### ISSUE TITLE
Can TF Privacy be used for generating synthetic data?

### ISSUE THREAD

**Issue by MaxGhenis** [tensorflow/privacy#24]
Congrats on today's launch! I'm involved in a [project](https://github.com/donboyd5/synpuf) to generate a synthetic version of a restricted dataset, to preserve privacy of the original data. A few months ago, we reviewed some of the research around differential privacy and synthetic data, and determined that it was too nascent to try to apply. Instead we've been synthesizing the dataset using simpler ML models like random forests to sequentially sample from the conditional distribution (our data is flat, and basically only has continuous features).

However, TF Privacy hitting the shelves seems like an advance worth us reconsidering our abandonment of DP. Has TF Privacy been used for synthesizing data before? To do it the way we've done it so far, we'd need to be able to predict quantiles, which we've seen some ways to do like [this blog post](https://towardsdatascience.com/deep-quantile-regression-c85481548b5a), and TF Probability seems promising too. I've used TF a bit, but we're not experts by any means, so we'd appreciate any guidance you can offer. Thanks!

**Comment by MaxGhenis** [comment]
For example, can TF Privacy be used with GANs?

**Comment by ilyamironov** [comment]
We encourage experimentation and, yes, TF Privacy can be used to train a GAN. Having said that, the success is by no means assured: training GANs is not easy, and training GANs with privacy is even harder. You may check out the following paper to appreciate some of the difficulties they had to solve: https://www.biorxiv.org/content/10.1101/159756v5.

**Comment by npapernot** [comment]
For the record, TF Privacy could also be used to train other generative models like VAE. As Ilya mentioned, it is not guaranteed that the overall process would produce a useful model though.
