### ISSUE TITLE
error during training teachers 

### ISSUE THREAD

**Issue by imaginedragontt** [tensorflow/privacy#28]
in the pate_2017, when i try to train teachers ,a error occured : in the deep_cnn.py , there is a module "from differential_privacy.multiple_teachers import utils", i thought it should be changed into "from pate_2017 import utils" since folder have changed , if i am wrong ,please let me know ,thx.

**Comment by npapernot** [comment]
Thanks for pointing this out, I'm rolling out a fix, it will automatically close this issue when it is rolled out to GitHub
