### ISSUE TITLE
tf.contrib.framework not found with tensorflow 2.0

### ISSUE THREAD

**Issue by strayMat** [tensorflow/privacy#30]
In lm_dpsgd_tutorial.py:
```
File "privacy/tutorials/lm_dpsgd_tutorial.py", line 45, in <module>
    from privacy.optimizers import dp_optimizer
  File "privacy/optimizers/dp_optimizer.py", line 22, in <module>
    from privacy.analysis import privacy_ledger
  File "privacy/analysis/privacy_ledger.py", line 29, in <module>
    nest = tf.contrib.framework.nest
AttributeError: module 'tensorflow' has no attribute 'contrib'
```
The [contrib module seems to have been deleted in tensorflow 2.0](https://pgaleone.eu/tensorflow/gan/2018/11/04/tensorflow-2-models-migration-and-new-design/). 
Is it still possible to call framework.nest from another module or should I downgrade tensorflow ?

**Comment by npapernot** [comment]
You are right, the `nest` module is now imported through `tf.nest`. Someone else pointed this out in #29 and I am rolling out a fix so I will close this issue for now (we will use #29 as a way to track this issue). The fix will roll out as soon as one of my colleague reviews it; most likely on Monday.
