### ISSUE TITLE
tf.train.AdagradOptimizer not found with tensorflow 2.0

### ISSUE THREAD

**Issue by guo-max** [tensorflow/privacy#33]
I know you fixed the tf.nest problem. But tf 2.0 also removed tf.train.AdagradOptimizer. Could you please do an update for this one as well?
here is the error log:
Traceback (most recent call last):
  File "mnist_dpsgd_tutorial_keras.py", line 55, in <module>
    from privacy.optimizers.dp_optimizer import DPGradientDescentOptimizer
  File "/data/repositories/privacy/privacy/optimizers/dp_optimizer.py", line 187, in <module>
    DPAdagradOptimizer = make_optimizer_class(tf.train.AdagradOptimizer)
AttributeError: module 'tensorflow._api.v2.train' has no attribute 'AdagradOptimizer'

**Comment by npapernot** [comment]
fix rolling out
