### ISSUE TITLE
changes to the Optimizer class API on tf2

### ISSUE THREAD

**Issue by npapernot** [tensorflow/privacy#35]
Because the Optimizer class was moved and does not have a `compute_gradients` method anymore: 

* the check for unchanged `compute_gradients` does not work anymore on tf2

* This will most likely mean we have to make a few changes to the calls we make (e.g., when we call compute_gradients for each microbatch). I haven't investigated this yet

**Comment by npapernot** [comment]
note: this can be reproduced using the alpha of tf2 on a cloud VM

**Comment by AnkitSiva** [comment]
Is there a workaround to this currently?

**Comment by npapernot** [comment]
A fix is rolling out
