### ISSUE TITLE
shape problem for Keras example

### ISSUE THREAD

**Issue by ebagdasa** [tensorflow/privacy#38]
tensorflow.python.framework.errors_impl.InvalidArgumentError: logits and labels must have the same first dimension, got logits shape [250,10] and labels shape [2500]

it looks different from other issues like: https://github.com/tensorflow/privacy/issues/17 and https://github.com/tensorflow/privacy/issues/27

**Comment by npapernot** [comment]
The shape of labels should be [250] if they are integers indicating the index of your label (i.e., 0, 1, 2, ... 9) or shape [250,10] if they are a one-hot vector where each vector is all 0s to the exception of the correct class which is set to 1 (if label is 2 and there are 10 classes: [0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

Would that explain the error here? Maybe you reshape the one hot labels to a 1D array but they should be a 2D array for a minibatch of data.

**Comment by ebagdasa** [comment]
yeah, thanks. I will try to look more into it.

**Comment by npapernot** [comment]
(feel free to reopen if your problem is not solved)

**Comment by cuizhiqiang888** [comment]
> (feel free to reopen if your problem is not solved)

how to fix it?
I met the same problem
