### ISSUE TITLE
Error using MNIST dataset parameters are same as given in MNIST DPSGD

### ISSUE THREAD

**Issue by sweetatyagiaz** [tensorflow/privacy#43]
I have just run the mnist_dpsgd_tutorial_keras.py file and I got this error.
kindly reply asap.
thanks in advance 

WARNING:tensorflow:From c:\users\tom-16s1\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From D:\DP\privacy\dp_query\gaussian_query.py:49: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
WARNING:tensorflow:From c:\users\tom-16s1\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\ops\array_grad.py:425: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
c:\users\tom-16s1\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\ops\gradients_impl.py:110: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Epoch 1/60
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-8-44cda3e31e6a> in <module>()
----> 1 tf.app.run()

c:\users\tom-16s1\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\platform\app.py in run(main, argv)
    123   # Call the main function, passing through any arguments
    124   # to the final program.
--> 125   _sys.exit(main(argv))
    126 

<ipython-input-7-0d23e46d6ce9> in main(unused_argv)
     49             epochs=FLAGS.epochs,
     50             validation_data=(test_data, test_labels),
---> 51             batch_size=FLAGS.batch_size)
     52 
     53   # Compute the privacy budget expended.

c:\users\tom-16s1\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, max_queue_size, workers, use_multiprocessing, **kwargs)
    878           initial_epoch=initial_epoch,
    879           steps_per_epoch=steps_per_epoch,
--> 880           validation_steps=validation_steps)
    881 
    882   def evaluate(self,

c:\users\tom-16s1\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, mode, validation_in_fit, **kwargs)
    327 
    328         # Get outputs.
--> 329         batch_outs = f(ins_batch)
    330         if not isinstance(batch_outs, list):
    331           batch_outs = [batch_outs]

c:\users\tom-16s1\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\backend.py in __call__(self, inputs)
   3074 
   3075     fetched = self._callable_fn(*array_vals,
-> 3076                                 run_metadata=self.run_metadata)
   3077     self._call_fetch_callbacks(fetched[-len(self._fetches):])
   3078     return nest.pack_sequence_as(self._outputs_structure,

c:\users\tom-16s1\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\client\session.py in __call__(self, *args, **kwargs)
   1437           ret = tf_session.TF_SessionRunCallable(
   1438               self._session._session, self._handle, args, status,
-> 1439               run_metadata_ptr)
   1440         if run_metadata:
   1441           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

c:\users\tom-16s1\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    526             None, None,
    527             compat.as_text(c_api.TF_Message(self.status.status)),
--> 528             c_api.TF_GetCode(self.status.status))
    529     # Delete the underlying status object from memory otherwise it stays alive
    530     # as there is a reference to status from this from the traceback due to

InvalidArgumentError: logits and labels must have the same first dimension, got logits shape [250,10] and labels shape [2500]
	 [[{{node loss/dense_1_loss/CategoricalCrossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]]

**Comment by npapernot** [comment]
Which version of TF are you using? From the stack trace, I'm guessing you are using Windows and Python 3.6. 

Did you make any changes to the tutorial itself?

**Comment by sweetatyagiaz** [comment]
Thanks for your response.
I have resolved the error. This was due to some version problem I think.

**Comment by zoeleeee** [comment]
@sweetatyagiaz Hi, I met the same problem with you. How did you solve it ?
My version:
Python 3.6.7
tensorflow 1.13.1
scipy 1.2.1
