### ISSUE TITLE
Inconsistency in released Versions between GitHub and PyPI

### ISSUE THREAD

**Issue by RobinBaumann** [tensorflow/privacy#443]
Hi, i just installed the latest version of tensorflow_privacy from PyPI. I found that the latest release on PyPI is version 0.8.8, while the latest release here on GitHub seems to be 0.8.5. Was there a change in the release process and this is expected or are the latest release notes simply missing?

Link to PyPI release history of TF Privacy: https://pypi.org/project/tensorflow-privacy/#history

**Comment by galenmandrew** [comment]
We just updated the GitHub release to 0.8.8. Sorry for the delay.
