### ISSUE TITLE
question about "tensorflow_privacy.privacy.dp_query.gaussian_query"

### ISSUE THREAD

**Issue by Yeojoon** [tensorflow/privacy#500]
I am trying to use the centralized (not local) Gaussian mechanism. Is "tensorflow_privacy.privacy.dp_query.gaussian_query" the right one for implementing the centralized continuous Gaussian mechanism?

Also, I think we can implement the centralized continuous Gaussian mechanism as below. 

------------------------------------------------------------------------------------

import tensorflow_federated as tff
from tensorflow_federated.python.aggregators import differential_privacy
from tensorflow_privacy.privacy.dp_query import gaussian_query

gaussian_query = gaussian_query.GaussianSumQuery(
    l2_norm_clip=l2_norm_clip, stddev=stddev)

factory = differential_privacy.DifferentiallyPrivateFactory(
   query=gaussian_query, record_aggregation_factory=tff.aggregators.UnweightedMeanFactory())

------------------------------------------------------------------------------------
Please check if this implementation is correct! Thank you for your time in advance.

**Comment by galenmandrew** [comment]
I don't see any problems in your code at a glance, but if you are using tff, it would be simpler to call `differential_privacy.gaussian_fixed`, which will handle all the `DPQuery` initialization for you. Also consider using `gaussian_adaptive`, which will do adaptive clipping so you don't need to choose a clip norm.

**Comment by Yeojoon** [comment]
I see. Thank you very much for your suggestions!
