### ISSUE TITLE
Federated DPFTRL and Adaptive Clipping noise injection.

### ISSUE THREAD

**Issue by BucketHeadP65** [tensorflow/privacy#519]
Dear developers of the privacy framework. I was checking the implementation of [quantile_adaptive_clip_tree_query.py](https://github.com/tensorflow/privacy/blob/master/tensorflow_privacy/privacy/dp_query/quantile_adaptive_clip_tree_query.py)

I can see that a new tree is required to inject noise after aggregating the norm bit as the traditional QuantileEstimatorQuery
is wrapped from the [TreeQuantileEstimatorQuery](https://github.com/tensorflow/privacy/blob/master/tensorflow_privacy/privacy/dp_query/quantile_estimator_query.py#L216)

In this paper [Federated Learning of Gboard Language Models with Differential Privacy](https://arxiv.org/abs/2305.18465) I see the paragraph highlighted in the image below. 
**Question:** Does this mean that I can just keep the logic of restarting the tree and then updating the clipping norm of the DPFTRL skipping the second tree that injects noise on norm bits and just replace the whole noise of Federated DP-FTRL with Adaptive clipping setup with just a Gaussian noise as stated in the figure? I am confused here.

Thanks you in advance.

![image](https://github.com/tensorflow/privacy/assets/104688161/a3c3d4d9-1396-40fb-9247-241d8a178403)

**Comment by BucketHeadP65** [comment]
Closing as it makes no senss, it says equivalent with **non-adaptive** DP-FTRL. damn

**Comment by nightldj** [comment]
Thanks for your interest. The noise multiplier is slightly inflated when using adaptive clipping as suggested in the theory. This can be done once similar to https://github.com/tensorflow/federated/blob/main/tensorflow_federated/python/aggregators/differential_privacy.py#L400
