### ISSUE TITLE
setting value of L2 clipping and noise multiplier

### ISSUE THREAD

**Issue by nguyenton68** [tensorflow/privacy#56]
What is the range of L2 clipping and noise multiplier?
I read from the tutorial, it was mentioned to use L2 = [0.3, 1.0] and noise = [0.3, ]
Are these parameters data independent?
Is there any relationship between them?
If I use L2/noise > 10, does it make any sense?

**Comment by npapernot** [comment]
You can find an explanation of the hyperparameters in the "Implementing DP-SGD with TF Privacy
" this blog post: http://www.cleverhans.io/privacy/2019/03/26/machine-learning-with-differential-privacy-in-tensorflow.html

If you still have questions after reading the blog post, feel free to reopen this issue and I'll be happy to provide more feedback.

**Comment by nguyenton68** [comment]
Thank you for your comment.
