### ISSUE TITLE
Probability of failure delta=1e-5 for MNIST dataset

### ISSUE THREAD

**Issue by NTT123** [tensorflow/privacy#71]
In many examples,  `delta` is set to `1e-5`. However, for MNIST dataset with 60k examples, we can easily guarantee (epsilon, delta)-dp  with `epsilon = 0` and `delta=1e-5` with the following mechanism:

- return a blank image with probability `1/2`
- return a random image in MNIST training set, each with probability `1 / 2/60k` ~ `8.3e-6`

This mechanism leaks a random image in MNIST with probability `1/2`.

To have a meaningful privacy guarantee, I think `delta` should be much smaller, e.g. `1e-7`.

**Comment by ilyamironov** [comment]
It's a fair point, and thank you for bringing it up.

You are right that the (0, delta)-DP definition allows releasing any record with probability delta. Or, in your example, a (0, 1/2N)-DP mechanism releases a random record with probability 50%.

Fortunately, this is not the behavior exhibited by our mechanisms! Concretely, they satisfy Renyi Differential Privacy, which implies (eps, delta)-DP for any delta > 0 (with epsilon depending on delta). You can play with compute_dp_sgd_privacy.py by plugging in various values of the delta parameter. For instance, for delta=1e-7 we have
```
$python compute_dp_sgd_privacy.py --N=60000 --batch_size=256 --noise_multiplier=1.1 --epochs=60 --delta=1e-7

DP-SGD with sampling rate = 0.427% and noise_multiplier = 1.1 iterated over 14063 steps satisfies differential privacy with eps = 3.55 and delta = 1e-07.
```
As you can see, the dependency on delta is relatively weak, and by convention, we use delta equal to the largest power of 10 not exceeding 1/N.

**Comment by schien1729** [comment]
Thanks for the explanation, Ilya! Closing this issue now. Please reopen if there's more to discuss.
