### ISSUE TITLE
Error running mnist_dpsgd_tutorial.py with TFr2.0

### ISSUE THREAD

**Issue by giulbia** [tensorflow/privacy#78]
Hi,

I set up a virtualenv with tensorflow 2.0.0 and tensorflow-privacy 0.1.0 (python version 3.7).
Inside the virtualenv I run `python mnist_dpsgd_tutorial.py` and I got serveral bugs linked to compatibility with TF2.0. I could correct some of them but then I can't follow up anymore. 

**BUGS IN `mnist_dpsgd_tutorial.py`**
- line 128 `tf.train.get_global_step()`
- line 176 `tf.logging.set_verbosity(tf.logging.INFO)`
- line 188 `train_input_fn = tf.estimator.inputs.numpy_input_fn(`
- line 194 `eval_input_fn = tf.estimator.inputs.numpy_input_fn(`

I modified `mnist_dpsgd_tutorial.py` as follows:
- line 128 `tf.compat.v1.train.get_global_step()`
- line 176 `tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.INFO)`
- line 188 `train_input_fn = tf.compat.v1.estimator.inputs.numpy_input_fn(`
- line 194 `eval_input_fn = tf.compat.v1.estimator.inputs.numpy_input_fn(`

**BUGS IN `privacy/analysis/tensor_buffer.py`**
- `File /<...>/privacy/analysis/tensor_buffer.py", line 56, in __init__
    initial_value=tf.placeholder_with_default(
AttributeError: module 'tensorflow' has no attribute 'placeholder_with_default'`
- `File "/<...>/privacy/analysis/tensor_buffer.py", line 60, in __init__
    use_resource=True)`
  `File "/<...>/tensorflow_core/python/ops/variables.py", line 260, in __call__
    return cls._variable_v2_call(*args, **kwargs)
TypeError: _variable_v2_call() got an unexpected keyword argument 'use_resource'`

I modified `privacy/analysis/tensor_buffer.py` as follows:
- line 56: `initial_value= tf.compat.v1.placeholder_with_default(`
- line 55: `self._buffer = tf.compat.v1.Variable(`
- line 61: `self._current_size = tf.compat.v1.Variable(`
- line 63: `self._capacity = tf.compat.v1.Variable(`

I have a new error and I don't know how to handle it. The optimizer variable is instatiated as `optimizer = dp_optimizer.DPGradientDescentGaussianOptimizer(<...>)` (`FLAGS.dpsgd` is True by default).
Here's the error:
`File "mnist_dpsgd_tutorial.py", line 129, in cnn_model_fn
train_op = optimizer.minimize(loss=opt_loss, global_step=global_step)
TypeError: minimize() got an unexpected keyword argument 'global_step'`

Thanks

**Comment by schien1729** [comment]
Hi giulbia@. We apologize for the delay in getting back to you. Thank you for documenting these bugs and your initial fixes. I'm working on fixing this now.

**Comment by schien1729** [comment]
Fixed with [this commit](url).

**Comment by giulbia** [comment]
Thank you @schien1729! FYI the link to commit in you previous comment is invalid.

**Comment by schien1729** [comment]
Oops, sorry about that. Here is the correct link:

https://github.com/tensorflow/privacy/commit/d69879d36011ab82dd15f3780bf7bb1ed7de83ca
