### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by nyeinsoe26** [tensorflow/privacy#83]
I have installed this package but I always encounter this error where it says module not found. How may i fix this?
![Capture](https://user-images.githubusercontent.com/54412199/68730506-dcf80180-0607-11ea-8e2a-cc5443f41920.PNG)

**Comment by kiddyboots216** [comment]
Probably should be `from tensorflow_privacy.privacy`

**Comment by npapernot** [comment]
The library was recently moved to tensorflow_privacy, you probably want to modify your imports as suggested.
