### ISSUE TITLE
apply DP to a set of layers

### ISSUE THREAD

**Issue by mofanv** [tensorflow/privacy#90]
Hi,

Thanks for the great project. I tried only to apply DP to parts of the DNN model, but I'm wondering **why this has the same privacy budget as applying DP to the whole DNN model? Is it needed to change the privacy accounting and corresponding code?**

As an example, Using DP when **(i)** training a new model from scratch and **(ii)** training the last FC layers of a pre-trained model (same DNN architecture) seems to have the same privacy budget based on moment accountant (if all parameters are the same, i.e., `n`, `q`, etc). However, they should not be the same, intuitively, since a different amount of noises are added. 

I see that Abadi's paper (2016) has added DP to the last layers, and the privacy accounting of the code mainly followed the Renyi DP paper, which I'm still trying to understand. 

Any suggestion is appreciated.
Thanks,
Fan

**Comment by npapernot** [comment]
If you are able to only train part of your DNN with privacy, this would not change how you analyze the privacy of that specific part of the DNN (you would also not get any privacy guarantees for the overall DNN if the layers that preceded the part which you trained with privacy were not trained with privacy and learned from private data). That said, even if the analysis does not change, you should be able to adjust the clipping norm and noise multiplier to get stronger privacy guarantees in practice—if the model you are training with privacy is smaller.
