### ISSUE TITLE
How can we perform attacks on model that is not trained with differential privacy?

### ISSUE THREAD

**Issue by carlodavid012** [tensorflow/privacy#95]
I followed the tutorial on training MNIST with DP-SGD. Once we computed the value of epsilon, interpreting this value is at times difficult. How to purposely insert secrets in the model’s training set and measure how likely they are to be leaked by a differentially private model (compared to a non-private model) at inference time?

**Comment by npapernot** [comment]
https://arxiv.org/abs/1802.08232
