### ISSUE TITLE
AdagradOptimizer = tf.compat.v1.train.AdagradOptimizer AttributeError: module 'tensorflow._api.v1.compat.v1.compat' has no attribute 'v1'

### ISSUE THREAD

**Issue by weizhanbiao** [tensorflow/privacy#98]
AdagradOptimizer = tf.compat.v1.train.AdagradOptimizer
AttributeError: module 'tensorflow._api.v1.compat.v1.compat' has no attribute 'v1'

what happen

**Comment by carlodavid012** [comment]
try to use `AdagradOptimizer = tf.train.AdagradOptimizer`
